#!/usr/bin/python3
import sys
import ctypes

lib = ctypes.CDLL("./libfactorize.so")
superFactorize = lib.factorize

def factorize(num):
    primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]
    for p in primes:
        if num % p == 0:
            return p
    num = superFactorize(ctypes.c_long(num))
    return num if num > 0 else None


if len(sys.argv) != 2:
    print(f"usage: {sys.argv[0]} <test-file>", file=sys.stderr)
    exit(1)

filename = sys.argv[1]
with open("tests/test00") as file:
    line = file.readline()
    while line:
        num = int(line.strip())
        q = factorize(num)
        if q is not None:
            p = num // q
            print(f"{num}={p}*{q}")
        line = file.readline()
